services:
  mariadb:
    image: mariadb:11.0
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: r00t123
      MYSQL_DATABASE: persona_db
    ports:
      - "3307:3306"
    volumes:
      - ./mysql/data/:/var/lib/mysql/:rw
      - ./scripts:/docker-entrypoint-initdb.d/:ro
    networks:
      - lab-network

  mongodb:
    image: mongo:7
    container_name: mongodb
    environment:
      - MONGO_INITDB_DATABASE=persona_db
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - "27017:27017"
    volumes:
      - ./mongo/mongodb:/data/db:rw
      - ./mongo/mongoconfig:/data/configdb:rw
      - ./scripts/persona_ddl_mongo.js:/docker-entrypoint-initdb.d/persona_ddl_mongo.js:ro
      - ./scripts/persona_dml_mongo.js:/docker-entrypoint-initdb.d/persona_dml_mongo.js:ro
    networks:
      - lab-network

networks:
  lab-network:
    driver: bridge
