version: "3.8"

services:
  mariadb:
    build:
      context: .
      dockerfile: db-config/maria/Dockerfile
    container_name: maria-lab
    environment:
      MYSQL_ROOT_PASSWORD: persona_db
      MYSQL_DATABASE: persona_db
      MYSQL_USER: persona_db
      MYSQL_PASSWORD: persona_db
    ports:
      - "3307:3307"
    networks:
      - lab-network

  mongodb:
    build:
      context: .
      dockerfile: db-config/mongo/Dockerfile
    container_name: mongo-lab
    environment:
      MONGO_INITDB_ROOT_USERNAME: persona_db
      MONGO_INITDB_ROOT_PASSWORD: persona_db
    ports:
      - "27017:27017"
    networks:
      - lab-network

networks:
  lab-network:
    driver: bridge
